// vue/vue3/todo-pinia/src/TodoFooter.vue
<script setup>
import { useTodos } from './stores/todos';

  let store = useTodos()
</script>

<template>
  <div>
   <span>{{ store.leftcount }} item{{ store.leftcount > 1 ? 's' :'' }} left</span>
   <div>
    <label><input type="radio" name="visible" value="all" v-model="store.visibleType">All</label>
    <label><input type="radio" name="visible" value="active" v-model="store.visibleType">Active</label>
    <label><input type="radio" name="visible" value="completed" v-model="store.visibleType">Completed</label>
   </div>
   <button v-if="store.hasCompleted" @click="store.clearCompleted">clear completed</button>
  </div>
</template>

<style scoped></style>

// reactjs/vite/my-react-todo-app/src/TodoFooter.tsx
import { useAtomValue,useAtom } from "jotai"
import { leftCountAtom ,hasCompletedAtom,todosAtom,visibleTypeAtom } from "./store"


export default function TodoFooter(){
  let leftCount = useAtomValue(leftCountAtom)
  let hasCompleted = useAtomValue(hasCompletedAtom)
  let [,setTodos] = useAtom(todosAtom)
  let [visibleType,setVisibleType] = useAtom(visibleTypeAtom)
  function clearCompleted(){
    setTodos(todos => todos.filter(todo => !todo.completed))
  }
  return <div>
    <span>{leftCount} item{leftCount > 1 ? 's' : ''} left</span>
    <div>
      <label><input type="radio" name="visibleType" checked={visibleType==='all'} onChange={()=>setVisibleType('all')} />All</label>
      <label><input type="radio" name="visibleType" checked={visibleType==='active'} onChange={()=>setVisibleType('active')} />Active</label>
      <label><input type="radio" name="visibleType" checked={visibleType==='completed'} onChange={()=>setVisibleType('completed')} />Completed</label>
    </div>
    {
      hasCompleted ? <button onClick={clearCompleted}>Clear Completed</button> : ''
    }
  </div>
}
