// vue/vue3/vue-todo-comps/src/TodoHeader.vue
<script setup>
  import { computed } from 'vue'
  let props = defineProps(['todos'])
  let isAllCompleted = computed(() => props.todos.every(e=>e.completed))
  let emit =  defineEmits(['toggle-All','add-todo'])
  function addTodo(e){
    let text = e.target.value.trim()
    if(text){
      emit('add-todo',text)
      e.target.value = ''
    }
  }
</script>

<template>
  <h1>Todo</h1>
  <div>
    <input type="checkbox" :checked="isAllCompleted" @change="$emit('toggle-All')">
    <input type="text" @keyup.enter="addTodo">
  </div>
</template>

<style scoped></style>

// reactjs/vite/my-react-todo-app/src/TodoHeader.tsx
import { useAtom } from "jotai"
import { isAllCompletedAtom, todosAtom } from "./store"
export default function TodoHeader(){
  const [isAllCompleted] = useAtom(isAllCompletedAtom)
  const [, setTodos] = useAtom(todosAtom)
  function toggleAll(){
    setTodos(todos => todos.forEach(todo=>(todo.completed =  !isAllCompleted)))
  } 
  function addTodo(e: React.KeyboardEvent<HTMLInputElement>){
    if(e.key === 'Enter'){
      const text = e.currentTarget.value.trim()
      if(text.length === 0){
        return
      }
      setTodos(todos => {
        todos.push({
          id: Date.now(),
          text,
          completed: false,
        })
      })
      e.currentTarget.value = ''
    }
  }
  return <div>
    <input type="checkbox"  checked={isAllCompleted} onChange={toggleAll}/>
    <input type="text" onKeyDown={addTodo} />
  </div>
}
