// vue/vue3/vue-todo-comps/src/TodoFooter.vue
<script setup>
  import { computed } from 'vue'
  let props = defineProps(['todos','visibleType'])
  defineEmits(['visibleType-change'])
  let showClearButton = computed(()=>props.todos.some(e=>e.completed))
  let Actnums = computed(()=>props.todos.filter(e=>!e.completed).length)
</script>

<template>
  <div>
   <span>{{ Actnums }} item{{ Actnums > 1 ? 's': '' }} left</span>
   <div>
    <label><input type="radio" name="visible" :checked="visibleType == 'All'" @click="$emit('visibleType-change','All')">All</label>
    <label><input type="radio" name="visible" :checked="visibleType == 'Active'" @click="$emit('visibleType-change','Active')">Active</label>
    <label><input type="radio" name="visible" :checked="visibleType == 'Completed'" @click="$emit('visibleType-change','Completed')">Completed</label>
   </div>
   <button v-show="showClearButton">clear completed</button>
  </div>
</template>

<style scoped></style>

// reactjs/vite/my-react-todo-app/src/TodoFooter.tsx
import { useAtomValue,useAtom } from "jotai"
import { leftCountAtom ,hasCompletedAtom,todosAtom,visibleTypeAtom } from "./store"


export default function TodoFooter(){
  let leftCount = useAtomValue(leftCountAtom)
  let hasCompleted = useAtomValue(hasCompletedAtom)
  let [,setTodos] = useAtom(todosAtom)
  let [visibleType,setVisibleType] = useAtom(visibleTypeAtom)
  function clearCompleted(){
    setTodos(todos => todos.filter(todo => !todo.completed))
  }
  return <div>
    <span>{leftCount} item{leftCount > 1 ? 's' : ''} left</span>
    <div>
      <label><input type="radio" name="visibleType" checked={visibleType==='all'} onChange={()=>setVisibleType('all')} />All</label>
      <label><input type="radio" name="visibleType" checked={visibleType==='active'} onChange={()=>setVisibleType('active')} />Active</label>
      <label><input type="radio" name="visibleType" checked={visibleType==='completed'} onChange={()=>setVisibleType('completed')} />Completed</label>
    </div>
    {
      hasCompleted ? <button onClick={clearCompleted}>Clear Completed</button> : ''
    }
  </div>
}
