// reactjs/vite/my-react-todo-app/src/TodoHeader.tsx
import { useAtom } from "jotai"
import { isAllCompletedAtom, todosAtom } from "./store"
export default function TodoHeader(){
  const [isAllCompleted] = useAtom(isAllCompletedAtom)
  const [, setTodos] = useAtom(todosAtom)
  function toggleAll(){
    setTodos(todos => todos.forEach(todo=>(todo.completed =  !isAllCompleted)))
  } 
  function addTodo(e: React.KeyboardEvent<HTMLInputElement>){
    if(e.key === 'Enter'){
      const text = e.currentTarget.value.trim()
      if(text.length === 0){
        return
      }
      setTodos(todos => {
        todos.push({
          id: Date.now(),
          text,
          completed: false,
        })
      })
      e.currentTarget.value = ''
    }
  }
  return <div>
    <input type="checkbox"  checked={isAllCompleted} onChange={toggleAll}/>
    <input type="text" onKeyDown={addTodo} />
  </div>
}

// vue/vue3/todo-pinia/src/TodoHeader.vue
<script setup>
 import { useTodos } from './stores/todos';
 let store = useTodos()
 function addTodo(e){
  let text = e.target.value.trim()
  if(text){
    store.addTodo(text)
    e.target.value = ''
  }
 }
</script>

<template>
  <h1>Todo</h1>
  <div>
    <input type="checkbox" @click="store.toggleAll" :checked="store.isAllCompleted">
    <input type="text" @keyup.enter="addTodo($event)">
  </div>
</template>

<style scoped></style>
